### ISSUE TITLE
Add Rest API and client bindings docs

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulp-docs#40]
We should have generated REST API and python client bindings reference on the docs.

I believe both REST API and client-bindings generation only depends on the openAPI json schema.

## Reference

- For client-bindings, we use [pulp-openapi-generator](https://github.com/pulp/pulp-openapi-generator), which can already produce a markdown docs (using [openapi-generator](https://github.com/OpenAPITools/openapi-generator)).
- REST API can be generated with several tools:
  - https://www.neoteroi.dev/mkdocs-plugins/web/oad/
  - https://github.com/bharel/mkdocs-render-swagger-plugin
  - $(\cdots)$

**Comment by dkliban** [comment]
We want to document the REST API, but I don't think we should worry about the bindings.

**Comment by pedro-psb** [comment]
Closed by #47
