### ISSUE TITLE
Add hot reload to pulp-docs serve

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulp-docs#9]
Because of the process of aggregation, mkdocs native hot-reload can't track the right files
It would be nice to have a workaround for this.

Three possible approaches are:
1. Dynamically re-configure mkdocs hot-reload (preferred)
2. Add `-w` option to pulp-docs to be passed to mkdocs (so watched files may be added manually)
3. Add an independent watching layer

**Comment by mdellweg** [comment]
If i can choose, I want 1 and 2.
(I believe they are not a contradiction and follow the watch behaviour of mkdocs.)
