### ISSUE TITLE
Linked page in github repo is to a site which doesnt exist https://pedro-psb.github.io/pulp-docs/

### ISSUE THREAD

**Issue by clintonsteiner** [pulp/pulp-docs#98]
Should be fixed and point to https://pulpproject.org

![image](https://github.com/user-attachments/assets/b8b6512a-2626-49d1-9945-4d631e4baa26)
https://github.com/pulp/pulp-docs

**Comment by pedro-psb** [comment]
Changed! Thanks for reporting
